version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ams_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sagore
      POSTGRES_DB: ams_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ams_app_container
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:sagore@db:5432/ams_db
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do
        sleep 2;
      done;
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
    name: postgres_data
